[package]
name = "insta"
version = "0.1.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
edition = "2018"

[features]
serialization = ["serde", "serde_yaml"]

[dependencies]
difference = "2.0.0"
serde = { version = "1.0.84", optional = true }
failure = "0.1.5"
serde_yaml = { version = "0.8.8", optional = true }
console = "0.7.2"
chrono = "0.4.6"
