[package]
name = "insta"
version = "0.3.0"
license = "Apache-2.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
description = "A snapshot testing library for Rust"
edition = "2018"
homepage = "https://github.com/mitsuhiko/insta"
repository = "https://github.com/mitsuhiko/insta"
keywords = ["snapshot", "testing", "jest"]
readme = "README.md"
exclude = [
    "assets/*"
]

[package.metadata.docs.rs]
all-features = true

[workspace]
members = [".", "cargo-insta"]

[features]
serialization = ["serde_yaml", "pest", "pest_derive"]

[dependencies]
difference = "2.0.0"
serde = { version = "1.0.84", features = ["derive"] }
failure = "0.1.5"
serde_yaml = { version = "0.8.8", optional = true }
console = "0.7.4"
chrono = "0.4.6"
serde_json = "1.0.36"
lazy_static = "1.2.0"
ci_info = "0.3.1"
pest = { version = "2.1.0", optional = true }
pest_derive = { version = "2.1.0", optional = true }

[dev-dependencies]
uuid = { version = "0.7.1", features = ["serde", "v4"] }
